### PR TITLE
Fix hardfault handler to SOS again

### PR DESCRIPTION
**Pull request by elcojacobs**
This fixes the broken hardfault handler as reported in #2380 

I added the `.align 4` line, which I think might be the actual fix for the compiler warning that the commit that introduced the bug intended to address.

It is very easy to test the hard fault handler, so it seems that the compiler warning was 'fixed' in the commit below without any testing! :fearful: 

https://github.com/particle-iot/device-os/commit/7b6e2086af907668d395c63404ecc754ee36fe41

I think that you are actually causing a hardfault in the hardfault handler now, resulting in an endless loop! @avtolstoy @sergeuz 

## Test app:

```cpp
void setup()
{
    int (*bad_instruction)(void) = nullptr;
    bad_instruction();
}

void loop()
{
    HAL_Delay_Milliseconds(1);
}
```

### CODE REVIEW

**Comment by elcojacobs** [comment]
It seems that the hardfault handler is part of the system layer, so it cannot be easily hotfixed without changing how the system layer is downloaded to the device. 
Because this is not fixable in the user app, we depend on Particle to do a hotfix release ASAP.

Or does the hardfault handler have weak linkage so we can override it?

**Review by sergeuz — APPROVED** [review]

**Comment by sergeuz** [comment]
Thanks for the PR, @elcojacobs. I'm not sure how this issue sneaked through testing, but your fix resolves it for me :+1:

**Comment by elcojacobs** [comment]
Thanks for merging the fix. Will build this into a release soon too?

**Comment by sergeuz** [comment]
> Will build this into a release soon too?

We will include this fix in the next 3.x release that we're hoping to get out this month.

**Comment by elcojacobs** [comment]
Can you please do better than 'this month'?

This is a critical bug that causes a complete device freeze. It causes large batches of beer to be ruined for my customers. Note that even the watchdog stops working with this bug.

You don't have to fast track 3.2.0 for me, just merge only the hardfault fix into the last release candidate.

**Comment by elcojacobs** [comment]
Can you discuss a hotfix release internally and inform us of the outcome?
This fix doesn't conflict with any other changes and should be an easy merge and release. I think the type of bug definitely warrants a hotfix release.

Waiting more than a week is unacceptable for my customers. If you cannot do a hotfix release, we have two options:

- Force all our customers to do a temporary flash over usb with hotfixed system images we compile ourselves. We already flash the user app over local wifi using ymodem, but the system layer comes from the cloud.
- Change the app to download the system images from our servers instead of particle. Where would we make that change and how should we host the binaries?

**Comment by sergeuz** [comment]
That's the only timeline I have at the moment, but the possibility of a hotfix release is being discussed in the context of your ticket for the original issue.

**Pull request merged**
