### PR TITLE
fix gcc6 build

### PR DESCRIPTION
**Pull request by kreopt**
**Summary of Commits:**
Fix build with gcc6
 - fix misleading indentation
 - add __gthread_recursive_mutex_timedlock signature to concurrent_hal_impl

**Problem:** 
Firmware does not build with gcc6
* in gcc6 -Werror=misleading-indentation is enabled by default and existing code  failed to build 
fixed
* c++ std library using __gthread_recursive_mutex_timedlock function which is not defined in firmware code

**Solution:** 

* remove redundand semicolon
* added __gthread_recursive_mutex_timedlock signature

---

Doneness:

- [x] Contributor has signed CLA
- [X] Problem and Solution clearly stated
- [ ] Code peer reviewed
- [x] API tests compiled
- [ ] Run unit/integration/application tests on device
- [x] Add documentation
- [ ] Add to CHANGELOG.md after merging (add links to docs and issues)

### CODE REVIEW

**Comment by harrisonhjones** [comment]
@kreopt Thanks for the PR. Can you update your top comment to follow the format below?

```
**Summary of Commits:**
Top level commit message
 - sub commit message 1
 - sub commit message 2
 - etc

**Problem:** Description of problem.

**Solution:** Description of solution.

---

Doneness:

- [ ] Contributor has signed CLA
- [ ] Problem and Solution clearly stated
- [ ] Code peer reviewed
- [ ] API tests compiled
- [ ] Run unit/integration/application tests on device
- [ ] Add documentation
- [ ] Add to CHANGELOG.md after merging (add links to docs and issues)
```

You should be able to literally just copy and paste everything in that dark grey box above into your edit, change it to suite your PR, and then submit. Thanks!

**Comment by kreopt** [comment]
done

**Comment by harrisonhjones** [comment]
Looks great. I believe the CLA has to be signed for this PR (or any PR) to be accepted. You can read about it [here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md). Do you think you can get that signed?

**Comment by sergeuz** [comment]
I would wait until ARM releases 6.x binaries officially on their [Launchpad page](https://launchpad.net/gcc-arm-embedded) before testing and merging this PR, rather than use any other distribution-specific binaries or upstream source code.

**Comment by kreopt** [comment]
> Do you think you can get that signed?
Yes, I think so. How can I do this?

**Comment by harrisonhjones** [comment]
@kreopt head on over to the [Particle Contributions](http://spark.github.io/#contributions) page and read the section near the bottom about signing the CLA.

**Comment by kreopt** [comment]
done

**Comment by sergeuz** [comment]
Looks like ARM decided to stop publishing their releases on Launchpad, and gcc 6.2.1 is actually available for download here: https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads. Sorry for the misleading comment that I posted above.

After making some additional changes I've managed to build the firmware with gcc 6.2.1, however, my Photon now freezes every time it tries to connect to a network.

Here is the branch that includes changes from this PR, as well as some other changes necessary to get the firmware built with gcc 6.2.1 specifically: https://github.com/spark/firmware/tree/fix/gcc_6.x

**Comment by technobly** [comment]
0.7.0-rc.1 will be targeting GCC 5.3.1

**Comment by elcojacobs** [comment]
This should really be included in 0.7.0

Apart from this small bug, I have no problem compiling on gcc 6.

ggc 5 has a nasty linker bug, which can cause lto-wrapper to fail on my build if I target the core.

**Comment by sergeuz** [comment]
@elcojacobs The firmware for the Photon compiled with GCC 6.x has network connectivity issues, which we haven't resolved yet. Currently, we're updating our default compiler only if the firmware compiled with it works reliably across all the platforms.

Could you describe the linker bug you mentioned?

**Comment by elcojacobs** [comment]
@sergeuz, thanks for the heads up. I'll revert back to gcc 5. Is gcc 5.4 2016-q3 considered stable? What is the recommended version?

I have a few customers that reported hard faults and we think it is wifi related. It seems to happen on the P1 with system 0.5.3 and system 0.7.0-rc2. It doesn't happen with the same software on the photon.

**Comment by elcojacobs** [comment]
I might have some info that could help uncover the wifi connectivity bug:
I show the IP address on a 2.8" TFT display, when connectivity was lost, it was shown as 0.0.0.0.
The device would still respond to ping, but not to TCP requests (refused).

This means WiFi.ready() returned `false` and WiFi.localIP() returned 0.0.0.0

**Comment by WarriorOfWire** [comment]
@sergeuz this moves toward GCC 7 compatibility.  Just leave your recommended GCC version alone if you want people to keep using 5 - but I have no problems with 7 beyond these banal firmware issues,  8 is going to be a bear looks like.  Can we get this merged?

**Comment by sergeuz** [comment]
Superseded by https://github.com/particle-iot/device-os/pull/1806

**Pull request closed without merging**
