### PR TITLE
feature/sc-101084/e404x-platform-toolchain-manifest

### PR DESCRIPTION
**Pull request by busticated**
### Problem

Local compiler toolchain does not recognize the new `esomx` platform

### Solution

Add the new `esomx` platform id to the list of supported platforms for the `deviceOS@source` toolchain

### Steps to Test

1. Follow the [installation instructions](https://github.com/particle-iot/cli/tree/main/packages/cli#installation) for CLI-vNext (aka "Delorean")
2. Install the `device@source` toolchain: `prtcl toolchain:install source:/path/to/device-os-repo` (consult `--help` if you need)
3. View and validate the `device@source` toolchain: `prtcl toolchain:view source:/path/to/device-os-repo --check` (consult `--help` if you need)
4. Follow the steps to enable the `deviceOS@source` toolchain within Particle Workbench ([docs](https://docs.particle.io/support/particle-tools-faq/workbench/#working-with-a-custom-device-os-build))
5. Follow the guide to compile and flash your firmware project using Particle Workbench ([docs](https://docs.particle.io/tutorials/developer-tools/workbench/#local-build-and-flash))
6. Observe [passing CI workflow](https://app.circleci.com/pipelines/github/particle-iot/device-os/677/workflows/f19d2d33-1443-41d0-88d3-47b640ef1caa)

**Outcome**

Toolchain should be installed and validated, you should be able to compile and flash via Particle Workbench while using the `deviceOS@source` toolchain. 

### References

https://app.shortcut.com/particle/story/101084/e404x-define-new-platform-and-platform-id-if-needed
https://github.com/particle-iot/device-os/pull/2443
https://github.com/particle-iot/device-os/pull/2449

---

### Completeness

- [x] User is totes amazing for contributing!
- [x] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [x] Problem and Solution clearly stated
- [ ] Run unit/integration/application tests on device
- [ ] Added documentation
- [ ] Added to CHANGELOG.md after merging (add links to docs and issues)

### CODE REVIEW

**Comment by scott-brust** [comment]
I'm using this branch of device-os with the `prtcl` cli v1.7.6. I can compile locally just fine when I specify both the DVOS source and the app dir to build:
```
prtcl compile:all source:/Users/scottbrust/develop/device-os/ esomx /Users/scottbrust/develop/device-os/user/applications/tinker
```

However when I omit the app dir (since the parameter appears to be optional?) The build fails. 
I dug into it and I believe it has to do with this line in the makefile:
```
# Set target build output directory
export TARGET_DIR = $(value APPDIR)/target/$(value DEVICE_OS_VERSION)/$(value PLATFORM)
```

Without an `APPDIR` the `TARGET_DIR` resolves to a subdir of wherever you happen to build from in the user module sources. I can see `TARGET_DIR` becomes this when building:
```
Running build task: "compile-all" for deviceOS@source [esomx] against undefined
- -
NVM_INC=/Users/scottbrust/.nvm/versions/node/v16.13.2/include/node
DEVICE_OS_PATH=/Users/scottbrust/develop/device-os
SHELL=/bin/zsh
_=/Users/scottbrust/.particle/toolchains/buildtools/1.1.1/make
...snip...
APPDIR=
...snip...
TARGET_DIR=/target/source/esomx
...snip...
```

The make step that fails is in `device-os/modules/boron/user-part/makefile` in the `prebuild` step where it tries to make a subdir for build output but does not have file permissions to do so (since it is still in the dvos source tree and not the user app dir or the /build/ output dir)
```
make[2]: Entering directory `/Users/scottbrust/develop/device-os/modules/boron/user-part'
mkdir -p /target/source/esomx/
mkdir: /target: Read-only file system
make[2]: *** [prebuild] Error 1
make[2]: Leaving directory `/Users/scottbrust/develop/device-os/modules/boron/user-part'
make[1]: *** [/Users/scottbrust/develop/device-os/modules/boron/user-part/makefile] Error 2
make[1]: Leaving directory `/Users/scottbrust/develop/device-os/modules'
make: *** [compile-all] Error 2
Command failed with exit code 2: make -f '/Users/scottbrust/.particle/toolchains/buildscripts/1.10.0/Makefile' compile-all
```

So the TL;DR is: When building locally it seems the DVOS source and APP dir are required? Should we default to using the empty user app in DVOS at `/user/src/application.cpp` if none is supplied?

**Comment by scott-brust** [comment]
Also none of this has to do with this PR, which seems good to me...

**Comment by busticated** [comment]
@scott-brust thanks for digging in 🙏 🙌 

> However when I omit the app dir (since the parameter appears to be optional?) The build fails.

it's optional if you are currently in your application's root directory:

```shell
cd /path/to/my-app
prtcl compile:all source:~/code/particle/device-os argon # note that in this case we can omit the PROJECTPATH arg
```

...i'll see if i can't make the help docs clearer 👍

**Comment by scott-brust** [comment]
I tried using this branch as device-os@source in workbench to try and build for `esomx` platform and get the following error
```
Invalid toolchain manifest!
Error: Invalid toolchain manifest!
	at module.exports.validateJSON (/Users/scottbrust/.vscode/extensions/particle.particle-vscode-core-1.14.9/node_modules/@particle/toolchain-manager/src/manifest/loader.js:103:9)
	at module.exports.mergeJSON (/Users/scottbrust/.vscode/extensions/particle.particle-vscode-core-1.14.9/node_modules/@particle/toolchain-manager/src/manifest/loader.js:66:3)
	at Object.module.exports.mergeOverrideFileSync (/Users/scottbrust/.vscode/extensions/particle.particle-vscode-core-1.14.9/node_modules/@particle/toolchain-manager/src/manifest/loader.js:88:9)
	at Function.mergeManifestForDeviceOSSync (/Users/scottbrust/.vscode/extensions/particle.particle-vscode-core-1.14.9/node_modules/@particle/toolchain-manager/src/toolchain.js:83:25)
	at loadManifestAndReportErrors (/Users/scottbrust/.vscode/extensions/particle.particle-vscode-core-1.14.9/src/index.js:165:13)
	at module.exports.activate (/Users/scottbrust/.vscode/extensions/particle.particle-vscode-core-1.14.9/src/index.js:32:3)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:17454)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:17119)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:14937
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async _activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8180)
	at async _waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8122)
	at async _initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:7486)

- - - -

[
    {
        "keyword": "hasValidPlatformID",
        "dataPath": ".toolchains[69].platforms[5]",
        "schemaPath": "#/definitions/platform_id/hasValidPlatformID",
        "params": {
            "keyword": "hasValidPlatformID"
        },
        "message": "should pass \"hasValidPlatformID\" keyword validation"
    }
]

- - - -
```

Is there something else that needs to be updated in workbench to allow building for `esomx`?

**Comment by busticated** [comment]
@scott-brust

> I tried using this branch as device-os@source in workbench to try and build for esomx platform and get the following error

i'm confused - [earlier in this PR](https://github.com/particle-iot/device-os/pull/2450#issuecomment-1128195160) you said:

>I'm using this branch of device-os with the prtcl cli `v1.7.6`. I can compile locally just fine when I specify both the DVOS source and the app dir to build

double-check that you indeed have this branch checked out locally, then run:

```shell
prtcl version # should output `v1.7.6`
prtcl toolchain:view source:<path-to-this-device-os-branch> --check # should show `esomx` in the list of supported platforms, all dependencies should be available and healthy
prtcl compile:all source:<path-to-this-device-os-branch> esomx <path-to-application> # should run the compilation
```

on my machine, `prtcl toolchain:view` returns:

```
deviceOS@source toolchain [✔ installed | × not installed]
for: photon, p1, electron, argon, boron, esomx, bsom, b5som, tracker

✔ gcc-arm@10.2.1
  * type: compilers
  * url: https://binaries.particle.io/gcc-arm/darwin/x64/gcc-arm-v10.2.1.tar.gz
  * root: /Users/me/.particle/toolchains/gcc-arm/10.2.1
  * main: ./bin
  * healthy: yes

✔ buildtools@1.1.1
  * type: tools
  * url: https://binaries.particle.io/buildtools/darwin/x64/buildtools-v1.1.1.tar.gz
  * root: /Users/me/.particle/toolchains/buildtools/1.1.1
  * main: .
  * healthy: yes

✔ buildscripts@1.10.0
  * type: scripts
  * url: https://binaries.particle.io/buildscripts/darwin/x64/buildscripts-v1.10.0.tar.gz
  * root: /Users/me/.particle/toolchains/buildscripts/1.10.0
  * main: .
  * healthy: yes

✔ openocd@0.11.2-adhoc6ea4372.0
  * type: debuggers
  * url: https://binaries.particle.io/openocd/darwin/x64/openocd-v0.11.2-adhoc6ea4372.0.tar.gz
  * root: /Users/me/.particle/toolchains/openocd/0.11.2-adhoc6ea4372.0
  * main: ./bin
  * healthy: yes
```

...and i'm able to compile

**Review by scott-brust — APPROVED** [review]
With WB `v1.14.10` i'm able to build for esomx 👍

**Review by tstellanova — APPROVED** [review]

**Pull request merged**
