### PR TITLE
[hal] concurrent: expose full concurrent APIs.

### PR DESCRIPTION
**Pull request by XuGuohui**
Expose the rest of concurrent HAL APIs.

### Completeness

- [x] User is totes amazing for contributing!
- [x] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [ ] Problem and Solution clearly stated
- [ ] Run unit/integration/application tests on device
- [ ] Added documentation
- [ ] Added to CHANGELOG.md after merging (add links to docs and issues)

### CODE REVIEW

**Comment by eberseth** [comment]
Please add conditional variable support as well

**Comment by avtolstoy** [comment]
@eberseth Conditional variable implementation is broken. We've previously agreed that we are not going to expose them. If we do require this feature for other work, we should prioritize changing the implementation.

We can always add the support in a separate PR.

**Comment by eberseth** [comment]
Okay, we'll use an alternate implementation.

**Comment by avtolstoy** [comment]
@eberseth Alternate implementation within concurrent HAL or outside of it?

**Comment by eberseth** [comment]
Perhaps copying out the cv implementation into user space versus using a standard library.

**Pull request merged**
